---

name: npm publish

# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - id: publish
        uses: onshape/actions-npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
